#!/usr/bin/env python3
"""
Create gitignored .env from a structured local api_keys.txt file.

Default source:
  C:\\Manasjit\\api_keys.txt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.config.key_file import REQUIRED_KEYS, parse_key_file

DEFAULT_SOURCE = Path(r"C:\Manasjit\api_keys.txt")
TARGET = ROOT / ".env"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate local .env from api_keys.txt")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env")
    return parser.parse_args()


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# AUTO-GENERATED by scripts/setup_local_env.py",
        "# DO NOT COMMIT",
        "",
    ]
    for key in REQUIRED_KEYS:
        lines.append(f"{key}={values[key]}")
    lines.extend(["", "EVAL_LLM_PROVIDER=openai", "EVAL_LLM_MODEL=", ""])
    TARGET.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    if TARGET.exists() and not args.force:
        print(f".env already exists at {TARGET}. Use --force to overwrite.")
        return 0

    try:
        values = parse_key_file(args.source)
        write_env(values)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {TARGET}")
    for key in values:
        print(f"  {key}: configured")
    print("Secrets are gitignored and were not printed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
